# Generated by Django 4.1.3 on 2022-12-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
